env:
  global:
    - CODECOV_TOKEN=b040177c-c3c6-4607-aeaa-7e85545b708f
language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: Sl5FUmA+sN1GNTbNtex1cRrwiMQoOYiXqW0GcBGgQsItkQGmL8K+ui6vZKDbtgtHBcqqPxXGrvZbLeJxaBoG66LaLeby1/YkFsGZXxxntplvtN/mUe4J4dKbz0dzoiaLjmPcwm83GoWop2jczcGaUDv09ZTh9Fj4quKAvlt3jZ14aHL5TD8SN0+ATdn20UTQP8zbiT9kqMJgga4Kra7VYcsG1tQ/+XgZps/6+/GXemX4nXX94LyXz2NsZiJUFcYMrEV7n2SrEkqAznDUF6RkItmtR0RLVx5ONtJNc2IISQDw8gKZZBYGXiu4pJwxePYuk25bnbgOERgpfqcpfNo76AadeVWcFZuO+ij78LeltqK5i6MFjP7zS0Wufucxlcblusvs1lKkDuEnXdAVZb15Bsmi+DGRt3jXK8j8SVgozmwbtgUHwCEW03mL8y7BAEK5Cmoa4URrbupXc7td29/2X61JNi7IarxzZb/KCoqinT/XV0O5t/J0cE1ZoIErD8cYNI7QiI+VJYWmvvB3EYqQUWNdiWfNXIaJTuK6Z0C8WGNXUgV0cr0bmDPXs56iV7ayrnUwpU3eSVirNv01iDGy7ZrEpFDsIqedbz1yYdgd5hB4F9PtVme5hohivdI4cxZl8I8+qPj9OVVHkgPw7MueMbdXvw4qULk2nALhWhPLiS8=
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build -i --continue
  - ./gradlew sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
