env:
  global:
    - CODECOV_TOKEN=9398368f-c443-4590-b225-5d88af52007e
language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: klindziukp-github
    token:
      secure: K6eutQvXufuSm5V+9+B0QcUPf5uYG/K9M/zeJsv1+A9JweKJmHDjAobTT87oF9tHSBYNo38Rdgjj090CaSgQeLGrYcrC2Ww/krXIhdly3BFDjv5+GFREW1Ulw94VdiiPXqib4nUGR3Xzr67BQS29S4fO7CfIPONljCarEA7qVquY8uG4GAiy7r/hZCkkJqYtapnladMq0e/4csYFS2gsGHDMArhiFmzsuYJYuxlsRmSfoPASL4ih7PYWdJfrkaiY7V4TRZfz2oxbQ0HiGra11sg3ab04Ggq8YL9G4YijPglKu4lTdI/gqQp+sdPpDQsb5RZOmzhTF/VUCHE/AP9n4x40SEAYw1cfPuKFY9seVent+MRQ4O1JJYVrKAvJsr482iyhQ4hMF0eZBU+T1kMJuwEqRTG8My4gxQf+Dk5dPpBJk0fDbYZDpBEhVdvMRUO1ZmUzp9Waf+Mp9FREpEYll1QbqxxvO2jbYKl9Y+sZJ9wFTN6/UCVhNlqTkw4Yv7yOswOVF7IUAue2W34O0UpgLZy3SyOWfjaonR1Ek6ff5UOWQUY6yYR0JdN+wHMBjVMK5/NBmddEZBXYlmAW2kEibO6cQUeLjsHvnaxvO7sPmjnQDp+0S9b9pGnjFlvP3cFfOx/8Qt6LsfWZioSU06IfKqaomYxydoIE+3HiQ59dEcE=
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build -i --continue
  - ./gradlew sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
