spring:
  datasource:
    url: jdbc:mysql://localhost:3306/evbx_product
    username: root
    password: root
server:
  servlet:
    context-path: /v1/evbx
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,flyway
service:
  resource:
    baseUrl: http://localhost:8002
    username: user
    password: user
