info:
  app:
    name: Evbx Product service
    description: REST Service for retrievieng ' Product ' information
    version: 0.0.1-SNAPSHOT

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/evbx_product
    username: root
    password: root
server:
  servlet:
    context-path: /v1/evbx
  port: 8009
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,flyway
service:
  resource:
    baseUrl: http://localhost:8002
    username: user
    password: user
